# general settings
server:
  port: 8080

# spring settings
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/transaction_db
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      use_sql_comments: true
      format_sql: true
      jdbc:
        time_zone: UTC
